create table if not exists public.payday_plans (id bigint generated by default as identity primary key, created_at timestamptz default now(), visitor_id text not null, input text not null, output text not null, input_tokens integer, output_tokens integer, identified_savings numeric default 0);
alter table public.payday_plans enable row level security;
grant select, insert, update, delete on table public.payday_plans to service_role;
create index if not exists payday_plans_visitor_idx on public.payday_plans(visitor_id);
